name: calib_tracker_dangote
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  auto_size_text: ^3.0.0
  dio: ^5.9.0
  ffi: ^2.1.3
  file_picker: ^10.3.1
  flutter:
    sdk: flutter
  get: ^4.6.6
  get_storage: ^2.1.1
  intl: ^0.20.0
  open_file: ^3.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Garnett
      fonts:
        - asset: assets/fonts/Garnett-Bold.ttf
          weight: 700
        - asset: assets/fonts/Garnett-Semibold.ttf
          weight: 600
        - asset: assets/fonts/Garnett-Regular.ttf
          weight: 400